// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtX6y5YBvt4F3G1azaOKyAmlBsuLMkeKA',
    appId: '1:593268337315:web:cf2782d096d8f39a16ed16',
    messagingSenderId: '593268337315',
    projectId: 'my-destinations-c13af',
    authDomain: 'my-destinations-c13af.firebaseapp.com',
    storageBucket: 'my-destinations-c13af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMbm9-OM0zyGzNAFzSAoROpKym7e6cydU',
    appId: '1:593268337315:android:bb3a4cbe09261ef016ed16',
    messagingSenderId: '593268337315',
    projectId: 'my-destinations-c13af',
    storageBucket: 'my-destinations-c13af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZcCw_z2_nkj2bODybRT1LzB5WR5Wa8Q',
    appId: '1:593268337315:ios:20b40e5aaa73f59c16ed16',
    messagingSenderId: '593268337315',
    projectId: 'my-destinations-c13af',
    storageBucket: 'my-destinations-c13af.appspot.com',
    iosBundleId: 'com.example.myDestinations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZcCw_z2_nkj2bODybRT1LzB5WR5Wa8Q',
    appId: '1:593268337315:ios:20b40e5aaa73f59c16ed16',
    messagingSenderId: '593268337315',
    projectId: 'my-destinations-c13af',
    storageBucket: 'my-destinations-c13af.appspot.com',
    iosBundleId: 'com.example.myDestinations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtX6y5YBvt4F3G1azaOKyAmlBsuLMkeKA',
    appId: '1:593268337315:web:410d0423d7e6c78616ed16',
    messagingSenderId: '593268337315',
    projectId: 'my-destinations-c13af',
    authDomain: 'my-destinations-c13af.firebaseapp.com',
    storageBucket: 'my-destinations-c13af.appspot.com',
  );

}